-- $BEGIN
INSERT INTO mamba_fact_tx_new (client_id,
                               weight_in_kg,
                               cd4_count,
                               current_who_hiv_stage,
                               nutritional_status,
                               tb_screening_result,
                               enrollment_date,
                               hiv_confirmed_date,
                               art_start_date,
                               days_difference,
                               followup_date,
                               regimen,
                               arv_dose_days,
                               pregnancy_status,
                               breast_feeding_status,
                               follow_up_status,
                               ti,
                               treatment_end_date,
                               next_visit_date,
                               latest_followup_date,
                               latest_followup_status,
                               latest_regimen,
                               latest_arv_dose_days)
SELECT client_id,
       MIN(CASE WHEN rn_asc = 1 THEN weight_in_kg END)          AS weight_in_kg,
       MIN(CASE WHEN rn_asc = 1 THEN cd4_count END)             AS cd4_count,
       MIN(CASE WHEN rn_asc = 1 THEN current_who_hiv_stage END) AS current_who_hiv_stage,
       MIN(CASE WHEN rn_asc = 1 THEN nutritional_status END)    AS nutritional_status,
       MIN(CASE WHEN rn_asc = 1 THEN tb_screening_result END)   AS tb_screening_result,
       enrollment_date,
       MIN(CASE WHEN rn_asc = 1 THEN hiv_confirmed_date END)    AS hiv_confirmed_date,
       MIN(CASE WHEN rn_asc = 1 THEN art_start_date END)        AS art_start_date,
       days_difference,
       MIN(CASE WHEN rn_asc = 1 THEN followup_date END)         AS followup_date,
       MIN(CASE WHEN rn_asc = 1 THEN regimen END)               AS regimen,
       MIN(CASE WHEN rn_asc = 1 THEN arv_dose_days END)         AS arv_dose_days,
       MIN(CASE WHEN rn_asc = 1 THEN pregnancy_status END)      AS pregnancy_status,
       MIN(CASE WHEN rn_asc = 1 THEN breast_feeding_status END) AS breast_feeding_status,
       MIN(CASE WHEN rn_asc = 1 THEN follow_up_status END)      AS follow_up_status,
       MIN(CASE WHEN rn_asc = 1 THEN ti END)                    AS ti,
       MAX(CASE WHEN rn_desc = 1 THEN treatment_end_date END)   AS treatment_end_date,
       MAX(CASE WHEN rn_desc = 1 THEN next_visit_date END)      AS next_visit_date,
       MAX(CASE WHEN rn_desc = 1 THEN followup_date END)     AS latest_followup_date,
       MAX(CASE WHEN rn_desc = 1 THEN follow_up_status END)     AS latest_followup_status,
       MAX(CASE WHEN rn_desc = 1 THEN regimen END)              AS latest_regimen,
       MAX(CASE WHEN rn_desc = 1 THEN arv_dose_days END)        AS latest_arv_dose_days
FROM (SELECT client_id,
             weight_in_kg,
             cd4_count,
             current_who_hiv_stage,
             nutritional_status,
             tb_screening_result,
             hiv_confirmed_date,
             art_start_date,
             followup_date,
             regimen,
             arv_dose_days,
             pregnancy_status,
             breast_feeding_status,
             follow_up_status,
             treatment_end_date,
             next_visit_date,
             ti,
             enrollment_date,
             days_difference,
             ROW_NUMBER() OVER (PARTITION BY client_id ORDER BY followup_date )     AS rn_asc,
             ROW_NUMBER() OVER (PARTITION BY client_id ORDER BY followup_date DESC) AS rn_desc
      from mamba_fact_art_follow_up) AS subquery

WHERE (rn_asc = 1 OR rn_desc = 1)
GROUP BY subquery.client_id;
-- $END
