-- $BEGIN
INSERT INTO mamba_fact_tx_new (client_id,
                               weight_in_kg,
                               cd4_count,
                               current_who_hiv_stage,
                               nutritional_status,
                               tb_screening_result,
                               enrollment_date,
                               hiv_confirmed_date,
                               art_start_date,
                               days_difference,
                               followup_date,
                               regimen,
                               arv_dose_days,
                               pregnancy_status,
                               breast_feeding_status,
                               follow_up_status,
                               ti,
                               treatment_end_date,
                               next_visit_date,
                               latest_followup_date,
                               latest_followup_status,
                               latest_regimen,
                               latest_arv_dose_days)
SELECT
    first_follow_up.client_id,
    first_follow_up.weight_in_kg,
    first_follow_up.cd4_count,
    first_follow_up.current_who_hiv_stage,
    first_follow_up.nutritional_status,
    first_follow_up.tb_screening_result,
    first_follow_up.enrollment_date,
    first_follow_up.hiv_confirmed_date,
    first_follow_up.art_start_date,
    first_follow_up.days_difference,
    first_follow_up.followup_date,
    first_follow_up.regimen,
    first_follow_up.arv_dose_days,
    first_follow_up.pregnancy_status,
    first_follow_up.breast_feeding_status,
    first_follow_up.follow_up_status,
    first_follow_up.ti,
    latest_follow_up.treatment_end_date,
    latest_follow_up.next_visit_date,
    latest_follow_up.followup_date,
    latest_follow_up.follow_up_status,
    latest_follow_up.regimen,
    latest_follow_up.arv_dose_days
FROM mamba_fact_art_first_follow_up first_follow_up
         JOIN mamba_fact_art_latest_follow_up latest_follow_up ON first_follow_up.client_id = latest_follow_up.client_id
GROUP BY first_follow_up.client_id;
-- $END
