-- $BEGIN
INSERT INTO mamba_fact_client (client_id,
                                      encounter_id,
                                      encounter_datetime,
                                      weight_in_kg,
                                      cd4_count,
                                      current_who_hiv_stage,
                                      nutritional_status,
                                      tb_screening_result,
                                      enrollment_date,
                                      hiv_confirmed_date,
                                      art_start_date,
                                      days_difference,
                                      followup_date,
                                      regimen,
                                      arv_dose_days,
                                      pregnancy_status,
                                      breast_feeding_status,
                                      follow_up_status,
                                      ti,
                                      treatment_end_date,
                                      next_visit_date,
                                      hiv_viral_load_count,
                                      hiv_viral_load_status,
                                      viral_load_test_status,
                                      on_antiretroviral_therapy,
                                      viral_load_test_indication,
                                      antiretroviral_side_effects,
                                      anitiretroviral_adherence_level,
                                      date_of_reported_hiv_viral_load,
                                      date_viral_load_results_received,
                                      routine_viral_load_test_indication,
                                      targeted_viral_load_test_indication,
                                      dsd_category,
                                      tpt_start_date,
                                      tpt_completed_date,
                                      tpt_discontinued_date,
                                      date_active_tbrx_completed,
                                      tb_prophylaxis_type,
                                      cotrimoxazole_prophylaxis_start_dat,
                                      cotrimoxazole_prophylaxis_stop_date,
                                      patient_diagnosed_with_active_tuber,
                                      diagnosis_date,
                                      tuberculosis_drug_treatment_start_d,
                                      fluconazole_start_date)
SELECT follow_up.client_id,
       follow_up.encounter_id,
       follow_up.encounter_datetime,
       weight_text_,
       cd4_count,
       current_who_hiv_stage,
       nutritional_status_of_adult,
       tb_diagnostic_test_result,
       date_enrolled_in_care,
       date_of_event,
       art_antiretroviral_start_date,
       DATEDIFF(art_antiretroviral_start_date,date_of_event) as days_difference,
       follow_up_date_followup_,
       regimen,
       antiretroviral_art_dispensed_dose_i,
       pregnancy_status,
       currently_breastfeeding_child,
       follow_up_status,
       why_eligible_reason_,
       treatment_end_date,
       next_visit_date,
       hiv_viral_load,
       hiv_viral_load_status,
       viral_load_test_status,
       on_antiretroviral_therapy,
       viral_load_test_indication,
       antiretroviral_side_effects,
       adherence,
       date_of_reported_hiv_viral_load,
       date_viral_load_results_received,
       routine_viral_load_test_indication,
       targeted_viral_load_test_indication,
       dsd_category,
       date_started_on_tuberculosis_prophy,
       date_completed_tuberculosis_prophyl,
       date_discontinued_tuberculosis_prop,
       date_active_tbrx_completed,
       tb_prophylaxis_type,
       cotrimoxazole_prophylaxis_start_dat,
       cotrimoxazole_prophylaxis_stop_date,
       patient_diagnosed_with_active_tuber,
       diagnosis_date,
       tuberculosis_drug_treatment_start_d,
       fluconazole_start_date
FROM mamba_flat_encounter_follow_up follow_up
         JOIN mamba_flat_encounter_follow_up_1 enc_follow_up_1        on enc_follow_up_1.encounter_id = follow_up.encounter_id
         JOIN mamba_flat_encounter_follow_up_2 enc_follow_up_2        on enc_follow_up_2.encounter_id = follow_up.encounter_id
         JOIN mamba_flat_encounter_follow_up_3 enc_follow_up_3        on enc_follow_up_3.encounter_id = follow_up.encounter_id
         JOIN mamba_flat_encounter_intake_a int_a on follow_up.client_id = int_a.client_id
where art_antiretroviral_start_date is not null;
-- $END
