name: Release OpenMRS Module on Tag

on:
  push:
    tags:
      - 'v*.*.*' # This workflow will run when a tag matching vX.Y.Z is pushed

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8 # Or the JDK version required by your module
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests # Build the module and create the OMOD

      - name: Get module version from POM
        id: get_version
        run: echo "MODULE_VERSION=$(mvn help:evaluate -q -Dexpression=project.version -P!standard-release-profile)" >> $GITHUB_ENV
        # This step extracts the project version from the pom.xml
        # We use -P!standard-release-profile to avoid issues with release profiles if they exist

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: omod/target/*.omod
          name: Release ${{ env.MODULE_VERSION }}
          tag_name: ${{ github.ref }} # Use the pushed tag as the release tag
          body: |
            ## Release Notes
            
            This release corresponds to version ${{ env.MODULE_VERSION }} of the OpenMRS module.
            
            Download the attached .omod file to install the module.
            
            Replace this text with more detailed release notes if needed.
          draft: false # Set to true to create a draft release
          prerelease: false # Set to true for pre-release versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this token